services:
  backend:
    image: matesrace-backend:latest
    container_name: matesrace-backend
    ports:
      - "8080:8080" # Exposes backend's port 8080 to host's port 8080
    environment:
      # Reference variables from the .env file
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME} # Using DB_NAME from .env
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - STRAVA_CLIENT_ID=${PROD_STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${PROD_STRAVA_CLIENT_SECRET}
      - FRONTEND_URL=http://localhost
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_STRAVA_REDIRECT_URI=http://localhost:8080/login/oauth2/code/strava
      # Add any other environment variables your backend needs
    depends_on:
      - db
    networks:
      - matesrace-network

  frontend:
    image: matesrace-frontend:latest
    container_name: matesrace-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - matesrace-network

  db:
    image: postgres:13
    container_name: matesrace-db
    environment:
      - POSTGRES_USER=${DB_USERNAME} # From .env
      - POSTGRES_PASSWORD=${DB_PASSWORD} # From .env
      - POSTGRES_DB=${DB_NAME} # From .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - matesrace-network

volumes:
  postgres_data:

networks:
  matesrace-network:
    driver: bridge
